apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - name: sentiment-api
        image: gcr.io/citric-campaign-455110-j7/sentiment-api
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-service
spec:
  type: LoadBalancer
  selector:
    app: sentiment-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
